version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - wget https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      - tar -xzf apache-maven-3.9.9-bin.tar.gz
      - mv apache-maven-3.9.9 /opt/maven
      - export PATH=/opt/maven/bin:$PATH
      - mvn -v

  pre_build:
    commands:
      - echo "Running pre-build commands..."

  build:
    commands:
      - echo "Building the project..."
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed successfully."
